[options]
attach = true
log_level = "debug"

[[pipelines]]
name =  "stylelint"

[[pipelines.steps]]
name = "styleing"
commands = ["bun stylelint styles/**/*.css"]

[[pipelines.triggers]]
actions = ["pre-push"]

[[pipelines]]
name = "watch"

[[pipelines.steps]]
[[pipelines.steps.parallel]]
name = "styles file watch"
commands = ["cd styles && bun vite build"]

[[pipelines.steps.parallel]]
name = "javascript serve"
commands = ["cd tera && bun vite build"]

[[pipelines.steps.parallel]]
name = "zola build"
commands = ["cd tera && zola build -u http://localhost:3000"]

#[[pipelines.steps]]
#name = "serve folder"
#commands = ["bunx serve tera/public"]

[[pipelines.triggers]]
actions = ["watch"]
