name = "karzok"
description = "A theme for your documentation. Fast and secure"
license = "MIT"
homepage = "https://github.com/kogeletey/karzok"
min_version = "0.15.0"
demo = "https://fmatch.org/karzok"

[extra]
show_word_count = true
show_reading_time = true

[author]
name = "Konrad Geletey"
