name = "karzok"
description = "The theme for launching fast documentation sites"
license = "MIT"
homepage = "https://github.com/kogeletey/karzok"
min_version = "0.15.0"
demo = "https://karzok.re128.org"

[extra]
show_word_count = true
show_reading_time = true

[author]
name = "Konrad Geletey"
