# Change to you title
title = "Re128 | Karzok"

description = "It will help speed up the development of a website and docs for your product"

base_url = "http://localhost:8080"


default_language = "en"

build_search_index = true

minify_html = true

compile_sass = false

#generate_feed = true

#feed_filename = "rss.xml"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[slugify]
paths = "safe"
anchors = "on"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

render_emoji = true


[languages.en]
build_search_index = true

[languages.en.translations]
description = "It will help speed up the development of a website and docs for your product"
toc_etp = "Edit this page"
toc_ita = "In this article"
date = "Date"
authors = "Authors"
updated = "Updated"
words = "words"

[languages.ru]
build_search_index = false

[languages.ru.translations]
description = "Тема для запуска быстрых сайтов документации"

toc_etp = "Редактировать страницу"
toc_ita = "В этой статье"
date = "Дата"
authors = "Aвторы"
updated = "Последние обновление"
words = "слова"

[extra]
# favicon
favicon = "assets/favicon.ico"

languages = ["en","ru"]

header_file = "content/header.toml"

#localcdn = true

show_word_count = true
show_reading_time = true
relative_path = true

repo = "https://github.com/kogeletey/karzok"
repo_branch = "develop"

announcement_file = "content/alert.toml"

[[extra.footer]]
lang = "en"
text = "powered by <a href=\"https://karzok.re128.org\"> karzok</a>"

[[extra.footer]]
lang = "ru"
text = "запущен с помощью <a href=\"https://karzok.re128.org\"> karzok</a>"

#[[extra.footer]]
#version = "https://api.github.com/repos/kogeletey/karzok/releases/latest"
