# https://github.com/woodpecker-ci/woodpecker/blob/master/.woodpecker/docker.yml
pipeline:
  push-rls:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org
      dockerfile: dist/Containerfile
      dry_run: false
      tag: rls
      logins:
        - registry: https://codeberg.org
          username:
            from_secret: cb_username
          password:
            from_secret: cb_password
        - registry: https://ghcr.io
          username:
            from_secret: gh_username
          password:
            from_secret: gh_password
    when:
      branch: release
      event: push
