on:
  push:
    branches:
      - develop

name: deploy to staging and build container
jobs:

  page-build:
    name: build theme
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: swc compile
      run: |
        npm ci
        npm run compile:js
    - name: link assets folder
      run: |
        npm run link:assets
        mv static/assets/CNAME static/CNAME
    - name: zola build
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: stg
        REPOSITORY: kogeletey/nebra
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_FLAGS: -u https://karzok.stg.re128.org
        #BUILD_ONLY: true
        #- name: postcss
        #run: |
        #npx postcss {main,page,section}.css --replace
  container-build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            "GITHUB_SHA=${GITHUB_SHA}"
            "GITHUB_REF=${GITHUB_REF}"
            "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
