on:
  push:
    branches:
      - develop

name: deploy to staging fmatch
jobs:
  build:
    name: zola build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: swc compile
      run: |
        npm ci
        npm run compile:js
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
